normer/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin', include(admin.site.urls)),
    url(r'', include('ratings.urls', namespace="ratings")),
)

ratings/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('ratings.views',
    url(r'question/(?P<image_id>\d+)$', 'question', name='question'),
    url(r'thanks$', 'thanks', name='thanks'),
    url(r'slideshow$', 'slideshow', name='slideshow'),
    url(r'slideshowb$', 'slideshowb', name='slideshowb'),
    url(r'^$', 'index', name='index'),
) 

ratings/models.py
from django.db import models
from datetime import datetime, timedelta

# Probably unnecessary, but I don't want to look this up and
# might need to change this in a minute
def default_create_time():
  return datetime.now()

class Subject(models.Model):
  created_at = models.DateTimeField(default=default_create_time)
  ip_address = models.GenericIPAddressField(null=True)

class Question(models.Model):
  # Images are now static files because fuck django
  image = models.IntegerField()
  subject = models.ForeignKey(Subject)

  # Actual question fields
  # Should rank 1 to 5

  name = models.CharField(max_length=50)
       
  recognizability = models.IntegerField()

  familiarity = models.IntegerField()

  pleasantness = models.IntegerField()

  complexity = models.IntegerField()

  memorability = models.IntegerField()

ratings/forms.py
from django import forms

class QuestionForm(forms.Form):
  image = forms.CharField(widget=forms.HiddenInput)

  recognizability = forms.TypedChoiceField(choices=((str(x), x) for x in range(1, 6)), coerce=int, widget=forms.RadioSelect)
  familiarity = forms.TypedChoiceField(choices=((str(x), x) for x in range(1, 6)), coerce=int, widget=forms.RadioSelect)
  pleasantness = forms.TypedChoiceField(choices=((str(x), x) for x in range(1, 6)), coerce=int, widget=forms.RadioSelect)
  complexity = forms.TypedChoiceField(choices=((str(x), x) for x in range(1, 6)), coerce=int, widget=forms.RadioSelect)
  memorability = forms.TypedChoiceField(choices=((str(x), x) for x in range(1, 6)), coerce=int, widget=forms.RadioSelect)

  name = forms.CharField(max_length=50)

ratings/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.utils import timezone

from ratings.models import Question, Subject
from ratings.forms import QuestionForm
from ipware.ip import get_ip
from IPython import embed

import logging
import random

logger = logging.getLogger(__name__)

# Create your views here.

def index(request):
  subject = Subject()
  ip = get_ip(request)
  if ip is not None:
    subject.ip_address = ip
  subject.save()
  request.session['subject_id'] = subject.id

  # Plan the test run (hardcoded to Experiment 1 for now)
  images = [i for i in xrange(1, 51)]
  random.shuffle(images)

  request.session['total_images'] = len(images)
  
  first_image = images[0]
  images = images[1:]

  request.session['image_order'] = images

  return render(request, 'ratings/index.html', {
    'first_image': first_image,
    'experiment_empty': False,
    'total_images': request.session['total_images'],
  })

# This provides the basic survey form
def question(request, image_id):
  if request.method == 'POST':
    form = QuestionForm(request.POST)
    # Check whether it's valid
    if form.is_valid():
      # SAVE IT
      question = Question()
      question.subject = Subject.objects.get(pk=request.session['subject_id'])
      question.image = form.cleaned_data['image']
      question.name = form.cleaned_data['name']
      question.recognizability = int(form.cleaned_data['recognizability'])
      question.familiarity = int(form.cleaned_data['familiarity'])
      question.pleasantness = int(form.cleaned_data['pleasantness'])
      question.complexity = int(form.cleaned_data['complexity'])
      question.memorability = int(form.cleaned_data['memorability'])

      question.save()

      # If this is the last question, direct the user to the THANKS page
      finished = False
      next_image = False
      if len(request.session['image_order']) > 0:
        next_image = request.session['image_order'][0]
        request.session['image_order'] = request.session['image_order'][1:]
      else:
        finished = True
      if finished:
        return HttpResponseRedirect('/thanks/')
      else:
        return HttpResponseRedirect('/question/' + str(next_image))
    else:
      # THERE ARE FORM ERRORS OMG WHAT DO WE DO
      return render(request, 'ratings/question.html', {
        'form': form,
        'image_path': image_id + '.jpg',
        'image_id': image_id,
        'images_left': len(request.session['image_order']), 
        'subject_id': request.session['subject_id'],
        'images': request.session['image_order']
        })
  else:
    image = image_id
    form = QuestionForm()
    return render(request, 'ratings/question.html', {
      'form': form,
      'image_path': str(image) + '.jpg',
      'image_id': image,
      'images_left': len(request.session['image_order']), 
      'subject_id': request.session['subject_id'],
      'images': request.session['image_order'],
      })

def thanks(request):
  return render(request, 'ratings/thanks.html')

def slideshow(request):
  return render(request, 'ratings/slideshow.html')

def slideshowb(request):
  return render(request, 'ratings/slideshowb.html')

ratings/templates/ratings/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <title>Cognition Lab Survey</title>
  </head>
  <body>
    <h1> Cognition Lab Survey </h1>

    <div class="instructions">
      <p>You will be shown a series of {{ total_images }} images. For each image, you will be asked to name the image and rank the image on several criteria. </p>
      <p>For each trait, rate the image for how accurately the trait describes it on a scale of 1 to 5, with 1 being Not at All, and 5 being Extremely.</p>
    </div>

    {% if experiment_empty %}
      <div class="empty_experiment"> Sorry, there are no images to rate at this time</div>
    {% else %}
      <div class="begin">
       <a href="{% url 'ratings:question' first_image %}">Begin!</a>
      </div>
    {% endif %}
  </body>
</html>

ratings/templates/ratings/question.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
  <title>Cognition Lab Norming Questions</title>
</head>
<body>
  <div class="image">
    <img src="{% static image_path %}" alt="Norming Image" />
  </div>
  <p style="display: none;"> {{ images }} </p>
  <p style="display: none;"> {{ subject_id }} </p>
  <form action = "/question/{{ image_id }}" method="post">
    {% csrf_token %}
    <div class="fieldWrapper">
      <input id="id_image" name="image" type="hidden" value="{{ image_id }}" />
    </div>
    <div class="fieldWrapper">
      {{ form.name.errors }}
      {{ form.name.label_tag }}
      {{ form.name }}
    </div>
    <div class="fieldWrapper">
      {{ form.recognizability.errors }}
      {{ form.recognizability.label_tag }}
      {{ form.recognizability }}
    </div>
    <div class="fieldWrapper">
      {{ form.familiarity.errors }}
      {{ form.familiarity.label_tag }}
      {{ form.familiarity }}
    </div>
    <div class="fieldWrapper">
      {{ form.pleasantness.errors }}
      {{ form.pleasantness.label_tag }}
      {{ form.pleasantness }}
    </div>
    <div class="fieldWrapper">
      {{ form.complexity.errors }}
      {{ form.complexity.label_tag }}
      {{ form.complexity }}
    </div>
    <div class="fieldWrapper">
      {{ form.memorability.errors }}
      {{ form.memorability.label_tag }}
      {{ form.memorability }}
    </div>
    <input class="button" type="submit" value="Next" />
  </form>
</body>
</html>

ratings/templates/ratings/slideshow.html
{% load staticfiles %}
<html lang="en" hola_ext_inject="inited">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>&nbsp;</title>
  <!-- Date: 2013-10-28 -->
  <style type="text/css">
    #instructions {
      font-size: 24px;
      width: 100%;
      text-align: left;
      margin-top: 10px;
      display: block;
    }
    #textcontainer {
      font-size: 64px;
      width: 100%;
      text-align: center;
      margin-top: 200px;
    }
    img {
      max-width: 300px;
      max-height: 300px;
    }
  </style>
  
  <script language="javascript">
  // replace this array with the srings you want to show - each element of the array is one slide
  var image_base = "/static/";
  var useA = true;

  var setA = new Array(
    '1.jpg',
    '11.jpg',
    '13.jpg',
    '16.jpg',
    '22.jpg',
    '23.jpg', 
    '25.jpg', 
    '31.jpg',
    '34.jpg',
    '35.jpg',
    '40.jpg',
    '43.jpg',
    '44.jpg',
    '46.jpg',
    '48.jpg',
    '49.jpg',
    '7.jpg',
    '9.jpg'
  );

  var setB = new Array(
    '10.jpg',
    '12.jpg',
    '14.jpg',
    '17.jpg',
    '21.jpg',
    '26.jpg',
    '29.jpg', 
    '3.jpg',
    '32.jpg',
    '33.jpg',
    '36.jpg',
    '37.jpg',
    '39.jpg',
    '4.jpg',
    '41.jpg',
    '42.jpg',
    '47.jpg',
    '8.jpg'
  );

  // number of seconds between slides
  var pause = 4;
  
  // control variables
  var timer = null;
  var numslides = 18;
  var currentslide = 0;
  
  // sets up the show - sets the variables to their initial state
  init = function() {
    timer = null;
    currentslide = 0;
    
    // hide the instructions
    document.getElementById("instructions").style.display = "none";
  }
  
  // function that shuffles the array of slide text
  // takes an array and returns an array
  shuffleArray = function(arr) {
    for (var i = 0; i < arr.length; i++) {
      var a = arr[i];
      var b = Math.floor(Math.random() * arr.length);
      arr[i] = arr[b];
      arr[b] = a;
    }
    return arr;
  }
  
  // window load function - start the show
  window.onload = function() {
    //startshow();
  };
  
  startshow = function() {
    // call the initialize function
    init();
    
    // call the function to shuffle the array
    if (useA) {
      setA = shuffleArray(setA);
    } else {
      setB = shuffleArray(setB);
    }
    
    // show the first slide
    advance();
  }
  
  // function advances to the next slide
  advance = function() {
    // increment the current slide number
    currentslide++;

    var image = ""
    if (useA) {
      image = setA[(currentslide-1)]
    } else {
      image = setB[(currentslide-1)]
    }
    
    // get the text that is to be displayed
    var txt = '<img src="' 
    //txt += 'file:///Users/Matt/school/spring15/PSYC4612/normer/normer/ratings/static/' + image + '" />';
    txt += image_base + image + '" />'
    
    // put the text inside the display DIV. innterHTML is good enough.
    document.getElementById("textcontainer").innerHTML = txt;
    
    // if we have not yet reached the end of the slides, call this function again;
    if (currentslide <= numslides) {
      timer = setTimeout(advance, pause*1000);
    } else {
      // call the function to reset
      reset();
    }
  }
  
  // resets to the initial state
  reset = function() {
    document.getElementById("textcontainer").innerHTML = "";
    document.getElementById("instructions").style.display = "block";
  }
  
  </script>
<style type="text/css"></style></head>
<body>
  <div id="instructions"><a href="#" onclick="startshow();">Start &gt;</a></div>
  <div id="textcontainer"></div>


</body></html>

ratings/templates/ratings/slideshowb.html
{% load staticfiles %}
<html lang="en" hola_ext_inject="inited">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>&nbsp;</title>
  <!-- Date: 2013-10-28 -->
  <style type="text/css">
    #instructions {
      font-size: 24px;
      width: 100%;
      text-align: left;
      margin-top: 10px;
      display: block;
    }
    #textcontainer {
      font-size: 64px;
      width: 100%;
      text-align: center;
      margin-top: 200px;
    }
    img {
      max-width: 300px;
      max-height: 300px;
    }
  </style>
  
  <script language="javascript">
  // replace this array with the srings you want to show - each element of the array is one slide
  var image_base = "/static/";
  var useA = false;

  var setA = new Array(
    '1.jpg',
    '11.jpg',
    '13.jpg',
    '16.jpg',
    '22.jpg',
    '23.jpg', 
    '25.jpg', 
    '31.jpg',
    '34.jpg',
    '35.jpg',
    '40.jpg',
    '43.jpg',
    '44.jpg',
    '46.jpg',
    '48.jpg',
    '49.jpg',
    '7.jpg',
    '9.jpg'
  );

  var setB = new Array(
    '10.jpg',
    '12.jpg',
    '14.jpg',
    '17.jpg',
    '21.jpg',
    '26.jpg',
    '29.jpg', 
    '3.jpg',
    '32.jpg',
    '33.jpg',
    '36.jpg',
    '37.jpg',
    '39.jpg',
    '4.jpg',
    '41.jpg',
    '42.jpg',
    '47.jpg',
    '8.jpg'
  );

  // number of seconds between slides
  var pause = 4;
  
  // control variables
  var timer = null;
  var numslides = 18;
  var currentslide = 0;
  
  // sets up the show - sets the variables to their initial state
  init = function() {
    timer = null;
    currentslide = 0;
    
    // hide the instructions
    document.getElementById("instructions").style.display = "none";
  }
  
  // function that shuffles the array of slide text
  // takes an array and returns an array
  shuffleArray = function(arr) {
    for (var i = 0; i < arr.length; i++) {
      var a = arr[i];
      var b = Math.floor(Math.random() * arr.length);
      arr[i] = arr[b];
      arr[b] = a;
    }
    return arr;
  }
  
  // window load function - start the show
  window.onload = function() {
    //startshow();
  };
  
  startshow = function() {
    // call the initialize function
    init();
    
    // call the function to shuffle the array
    if (useA) {
      setA = shuffleArray(setA);
    } else {
      setB = shuffleArray(setB);
    }
    
    // show the first slide
    advance();
  }
  
  // function advances to the next slide
  advance = function() {
    // increment the current slide number
    currentslide++;

    var image = ""
    if (useA) {
      image = setA[(currentslide-1)]
    } else {
      image = setB[(currentslide-1)]
    }
    
    // get the text that is to be displayed
    var txt = '<img src="' 
    //txt += 'file:///Users/Matt/school/spring15/PSYC4612/normer/normer/ratings/static/' + image + '" />';
    txt += image_base + image + '" />'
    
    // put the text inside the display DIV. innterHTML is good enough.
    document.getElementById("textcontainer").innerHTML = txt;
    
    // if we have not yet reached the end of the slides, call this function again;
    if (currentslide <= numslides) {
      timer = setTimeout(advance, pause*1000);
    } else {
      // call the function to reset
      reset();
    }
  }
  
  // resets to the initial state
  reset = function() {
    document.getElementById("textcontainer").innerHTML = "";
    document.getElementById("instructions").style.display = "block";
  }
  
  </script>
<style type="text/css"></style></head>
<body>
  <div id="instructions"><a href="#" onclick="startshow();">Start &gt;</a></div>
  <div id="textcontainer"></div>


</body></html>

ratings/templates/ratings/thanks.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
  <title>Cognition Lab Survey Completion</title>
</head>
<body>
<h1> Thanks for completing our survey! </h1>
</body>
</html>